### ISSUE TITLE
For what is worth..

### ISSUE THREAD

**Issue by foo123** [braydie/HowToBeAProgrammer#109]
If not, then delete this issue-comment.

Change the title to `HowToBeAnEmployee` or even `HowToBeAnEmployeeInCompaniesWithLargeGlassWallsForWhichThereAreNoPeopleButEitherResourcesOrClients`

**Comment by braydie** [comment]
Hey @foo123  I'm not sure I really understand the issue here. I'm going to keep the title as it is for now as it is fairly succinct and to the point.

**Comment by foo123** [comment]
Yes, the comment is about the fact that programming is not about being an employee (which is a large part of the document). Programming is about programming. Being a (dependent) employee in a company, maybe be just one way for (professional) programming. Not the only way and certainly not the best way. Especialy judging from companies were people (employees) are just *human resources*. Not to mention the fact of intellectual rights to one's own work, usualy asked to hand them over to the company. That was the meaning of the comment. So i stick to my comment for this.
