### ISSUE TITLE
How to be Trustworthy - typo "know" should be "no".

### ISSUE THREAD

**Issue by CameronHall** [braydie/HowToBeAProgrammer#11]
HowToBeAProgrammer/2-Intermediate/Personal-Skills/02-How to be Widely Trusted.md

First line should read "To be trusted you must be trustworthy. You must also be visible. If **no** one knows about you, no trust will be invested in. Rather "To be trusted you must be trustworthy. You must also be visible. If **know** one knows about you, no trust will be invested in "

Love your stuff guys :+1: :)

**Comment by braydie** [comment]
Hey Cameron, this was fixed by a pull request from @AlecHansen :)
