### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DStranger** [braydie/HowToBeAProgrammer#115]
Links [here](https://braydie.gitbooks.io/how-to-be-a-programmer/content/en/) are broken, nothing happens when you click them. Consecutively, pdf, mobi and ePub versions are only 13 pages long.

**Comment by braydie** [comment]
Oh man thanks for the heads up @DStranger! That sucks. I'll take a look and see what I can do. We recently updated all the links github stopped encoding the spaces so we had to put lots of %20s into the URLs to get github to render them correctly - I suspect that might be the cause...

**Comment by braydie** [comment]
@SamyPesse is this something you've seen affecting other repos on gitbook? Or am I barking up the wrong tree with this one....?

**Comment by braydie** [comment]
So a little poking around and it looks like it's because we're using spaces in the markdown filenames. Will just wait to see if this is something can be changed on gitbook. Failing that I will write something to update all the links to use dashes instead of spaces which should fix the problem

**Comment by braydie** [comment]
Hey @DStranger I've pushed a fix through so gitbook should update soon and you'll be able to read online and download the full version of the book! Thanks for raisin the issue!

**Comment by DStranger** [comment]
@braydie awesome, thanks!
