### ISSUE TITLE
Copy from old Korean translation (GFDL)

### ISSUE THREAD

**Issue by ikasty** [braydie/HowToBeAProgrammer#119]
As mentioned from [this(#45)](https://github.com/braydie/HowToBeAProgrammer/issues/45#issuecomment-172314339) comment, Korean translation exists already (https://wiki.kldp.org/wiki.php/HowToBeAProgrammer). It is stored in wiki page using Korean, however I believe that copying from it to here is valuable enough for everyone.

Only I worried is the copyright; it uses GFDL compared to the cc-by-sa used in here. Is this possible to copy to here?

**Comment by braydie** [comment]
I agree with you completely - bringing the Korean translation in here would be great, although it looks like this version was translated from Roberts original essay and not this repository. The version we have here now has a number alterations and additions (and is licensed differently) that may not be reflected in the Korean translation you've linked. 

It would be a good idea to reach out to the author of the translation to see if they would consider re-licensing to be CC-by-SA. I don't think GFDL aligns itself with the purpose of this essay.

**Comment by ikasty** [comment]
Okay great. I will consider both contact to the author and translate this version by myself :D
