### ISSUE TITLE
GitBook Export Links Broken

### ISSUE THREAD

**Issue by chrisfeltner** [braydie/HowToBeAProgrammer#125]
Hello! Thank you so much for open sourcing and maintaining this great guide!

The [link](https://www.gitbook.com/book/braydie/how-to-be-a-programmer/details) on the README for PDF export appears to be broken and sends the user to the GitBook homepage.

**Comment by braydie** [comment]
Hey @chrisfeltner thanks for letting me know, I've updated the link however PDF export is now a paid gitbook feature. I will look at generating PDF and other formats when I have the time
