### ISSUE TITLE
convert to PDF format

### ISSUE THREAD

**Issue by vickydasta** [braydie/HowToBeAProgrammer#15]
could you please convert all of the content into one single PDF file? thanks!

**Comment by vickydasta** [comment]
hey, i've write a script to convert all markdown files on this repository https://github.com/vickydasta/HowToBeAProgrammer.pdf

**Comment by braydie** [comment]
Hey @vickydasta, sounds like a good idea. It would be nice to be able to offer the guide as a single document. What you've done looks like the right approach - using something like node will help us remain platform agnostic.

**Comment by braydie** [comment]
In the next week or so I'll try and figure out how we can either include what you've written, or put our own thing in place

**Comment by vickydasta** [comment]
@braydie :+1:

**Comment by braydie** [comment]
Hi @vickydasta, the repository is now available to [download as a PDF via gitbook.com](https://www.gitbook.com/download/pdf/book/braydie/how-to-be-a-programmer)

**Comment by vickydasta** [comment]
good to know that. thanks for your great work, cheers! @braydie
