### ISSUE TITLE
Post each one of these in medium

### ISSUE THREAD

**Issue by haikyuu** [braydie/HowToBeAProgrammer#16]
[Medium.com](medium.com) is the perfect place for this material to be. It has awesome **reader experience** and gives the ability to **highlight** and **comment** anything. You could provide a link to each medium post in the `README.md`

What do you think?

**Comment by haikyuu** [comment]
Here is [the first chapter](https://medium.com/@AlaouiSolaimani/learn-to-debug-5b405afefa6b#.79cy1mmcw) in Medium

**Comment by braydie** [comment]
Hey @haikyuu, I'm a massive fan of Medium - I literally have their t-shirt - but I think for ease of updating and involving a community, we'll keep GitHub as the primary place for this guide. However, feel free to use the topics here as inspiration and write something on Medium (or contribute it to this repo via a pull request!) :)
