### ISSUE TITLE
Moving to a GitBook version

### ISSUE THREAD

**Issue by howiehu** [braydie/HowToBeAProgrammer#34]
Hi, I think you can moveing you book to a GitBook version.

It will be more easier reading and writing:

https://github.com/GitbookIO/gitbook

**Comment by RobertLRead** [comment]
This is a very interesting idea.  I'm not sure I have time to do it, but I will try to study the idea.

**Comment by SamyPesse** [comment]
:+1: 

I'll be happy to make a PR for this (It'll basically be the addition of a `SUMMARY.md`).

**Comment by xcatliu** [comment]
Nice idea!

**Comment by braydie** [comment]
Sounds like a good idea. GitBook does look good - and I think would certainly provide a nicer reading experience than just straight up MarkDown

**Comment by dufferzafar** [comment]
:+1: 

Doing this will also allow us to fix #15 as gitbook can be easily exported to [pdf (& other formats like epub)](https://github.com/GitbookIO/gitbook#output-formats) :smiley:

**Comment by vickydasta** [comment]
:+1:  would be nice! :smile:

**Comment by vasco3** [comment]
Took me a couple of hours to learn how GitBook works and hook my GitHub repo into a nice GitBook. Totally recommend it.

### Example
- [Github repo](https://github.com/vasco3/hacks-n-notes/)
- [Converted to GitBook](https://www.gitbook.com/book/vasco3/hacks-n-notes/welcome)

**Comment by JaKXz** [comment]
Love this, and would love to see it on Gitbook! :D

**Comment by derek-damron** [comment]
:+1:

**Comment by ImDineshSaini** [comment]
It is good but we need a different account :(

**Comment by braydie** [comment]
Hi all, I've merged @SamyPesse work into `master` and created a gitbook for the repository - https://www.gitbook.com/book/braydie/how-to-be-a-programmer/details. I think there is still some work to do in terms of tidying up how the book looks (and we can look to drop the paging stuff I was trying to do between the sections as gitbook handles that for us)

**Comment by SamyPesse** [comment]
@braydie Awesome :beers: :rocket: Let me know what improvements are you think about?
The obvious one is to fix the grey links in the sidebar, but we'll probably fix it in the next release of GitBook (you don;t need to remove the paging stuff).

@ImDineshSaini You don't need another account, contributions should always be done on the GitHub repository; GitBook simply offers a better reading experience, PDF output, etc (and keep the output in sync with the GitHub repository).

**Comment by howiehu** [comment]
@SamyPesse nice work!

I believe add i18n support will be better. :smile: 

Or it can be adding when I to translate this book to Chinese.

**Comment by braydie** [comment]
@SamyPesse a few things, maybe try and get a nice cover created, consolidate some of the glossary terms (I love that gitbook collates them and shows usage of terms through the book!) and maybe look to see if there is anything we can do regarding references. It looks so good as a gitbook! 

Also, I think I messed up on merging your pull request as it is still listed on github even though I've merged it..?

**Comment by braydie** [comment]
Got your PR properly merged in @SamyPesse :+1:
