### ISSUE TITLE
Proposed new section - Functional Reactive Programming

### ISSUE THREAD

**Issue by ImDineshSaini** [braydie/HowToBeAProgrammer#43]
Most of the enterprises using the same technique to implement so don't you think we should add this section too?

**Comment by RobertLRead** [comment]
Dear @ImDineshSaini,

I think Functional Reactive Programing is a little too new and obscure to go into this work.  But let me make a counter proposal: every programmer needs to understand map-reduce (and fold, IMHO.)  May I suggest that we make a section on those basic operations of functional programming?  I think that is more fundamental to programming itself.

**Comment by ImDineshSaini** [comment]
I agree with your concerns however it is not a new concept Microsoft and
others introduced it in 1998. At that time we have limitations to use FRP
because it demand more memory as compare to general programming. We can add
it in the expert system and also divide the section as: Functional
Programming, Reactivate Programming and then Functional Reactive
Programming. I have given a seminar in Ruby Conference India and I can
share the shame with you. Please drop your email to mine. Me@dineshsaini.net

**Comment by ImDineshSaini** [comment]
@RobertLRead I m closing the ticket as not able to hear from your side,
