### ISSUE TITLE
Tool for exporting?

### ISSUE THREAD

**Issue by olivif** [braydie/HowToBeAProgrammer#64]
I was thinking it would be nice to have the whole "book" into one file.

What if we write a little script to go through a folder and pack all of the .mds into one master .md or a pdf of whatever else? We could even add that as a build task so for every build we export a new final version.

**Comment by ahangchen** [comment]
Here is the [gitbook](https://www.gitbook.com/book/braydie/how-to-be-a-programmer/details) linked to  the repository. Maybe it's a better choice.

**Comment by olivif** [comment]
Oh sweet, I didn't know this existed. Thanks!
