### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by bhargavrpatel** [braydie/HowToBeAProgrammer#67]
Hello, 

Even though this is still being worked on,  I would love if there was a way for me to read this offline on my kindle. 

Regards, 
BRP

**Comment by nkartashov** [comment]
@bhargavrpatel one can paste all the markdown into one file and convert it to PDF with pandoc. Although it would be better if a PDF version was available out-of-the-box.

**Comment by ahangchen** [comment]
@bhargavrpatel @nkartashov This book has been published on [gitbook](https://www.gitbook.com/book/braydie/how-to-be-a-programmer/details)(Click this). You can easily export it into a pdf by gitbook. Maybe a link for gitbook in the introduction will be better.

**Comment by nkartashov** [comment]
@ahangchen Thanks!

**Comment by bhargavrpatel** [comment]
@ahangchen  Thanks. I did see the Gitbook page but unfortunately I did not see the right section allowing saving as pdf/epub/mobi as I was browsing on my Android. 

Thank you very much; closing issue.
