### ISSUE TITLE
Add semantic version numbers to pages

### ISSUE THREAD

**Issue by braydie** [braydie/HowToBeAProgrammer#75]
As per @xmalinov - https://github.com/braydie/HowToBeAProgrammer/issues/45#issuecomment-171892970 for keeping translated versions of the guide in sync

**Comment by braydie** [comment]
Github-flavoured markdown doesn't support metadata, so it looks like I may need to add inline HTML into each file for the version number, either using `<meta name="version" content="1.0.0" />` or something bespoke like `<version number="1.0.0" />`. Has anyone come across this sort of thing before or know of a better approach for including version numbers?

**Comment by ajsebastian** [comment]
Hi! If you still need help doing this I would be more than willing to run through and insert this into the files.

**Comment by braydie** [comment]
hey @ajsebastian, the issue that I've yet to resolve is how to add the version numbers so that they don't impact the readability of the pages on github or gitbook -- ideally, I want to be able to add the version numbers as metadata so that it doesn't render on the page

**Comment by ajsebastian** [comment]
@braydie That makes a lot more sense. After looking into it for a while it seems that the best way to add comments to markdown files which won't appear in the github page (it will still show in the raw data) is to format your comments like this:  [//]: # (This may be the most platform independent comment) .
Everything inside of the parenthesis will not show unless you look at the raw data. I tested on a markdown file in a test directory here: https://github.com/ajsebastian/ajsebastian.github.io/blob/master/Comment%20showcase.md and it seems to work in the Github environment. You can see the comments by going to the raw or blame tabs. Let me know if this helped!

**Comment by ajsebastian** [comment]
If you give me the version numbers and are satisfied with the comment method i could take this issue and update all of the files ASAP.

**Comment by ajsebastian** [comment]
I submitted a pull request of a version of the project where every file has a version number comment at the top. Hope this was helpful.

**Comment by braydie** [comment]
@ajsebastian that is awesome! I think there are probably a few differences between the English and Chinese version at present just down to natural drifting within each section, which we will just have to accept for the time being. Thank you so much for figuring this out! I'm tied up this weekend but will review and merge in the coming week!
